#!/bin/sh

set -o nounset
set -o errexit

export MODIFIED=$(git diff --exit-code ./README.txt | awk 'END{if (NR > 0) {print "true"} else {print "false"}}')
echo "UPADTE CHANGES: ${MODIFIED}"
if [[ "$MODIFIED" == "true" ]]; then
  echo "UPADTE CHANGES: ${MODIFIED}"
  git status
  git add ./README.txt
  git config user.email "${MICHAWAI_REPO_USER_EMAIL}"
  git config user.name "${MICHAWAI_USER}"
  git commit --allow-empty -m "[skip ci] update go.sum"
  #Push commit directly to current branch
  git push -q https://github.com/michawai/aaa.git ${CIRCLE_BRANCH}
fi
